### ISSUE TITLE
Erro: WebDriverException: Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1

### ISSUE THREAD

**Issue by IHateNameStealers** [TechMaz/youtube-live-chat-scraper#1]
I'm having issues running your code :-(
Ubuntu 19.04

`root@noel-PowerEdge-R210:/home/noel/git/youtube-live-chat-scraper# python app/routes.py
 * Serving Flask app "routes" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-05-10 13:42:05,779] ERROR in app: Exception on /scrape/aWZqLSAccng [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app/routes.py", line 18, in scrape
    chats = scraper.run_scraper(id)
  File "/home/noel/git/youtube-live-chat-scraper/app/scraper.py", line 37, in run_scraper
    browser = webdriver.Chrome(executable_path=chromedriver_path,chrome_options=chrome_options,service_args=service_args,service_log_path=service_log_path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1
`

Any suggestion what it could be or how to debug? I'm not really an expert.
Thank you.

**Comment by IHateNameStealers** [comment]
Nevermind. I found the problem.
I did not have the directory **/var/www/logs**
After creating it, all started to work fine!
